# Generated by Django 5.1.4 on 2025-06-11 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_airportpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_zone', models.CharField(choices=[('TERMINAL', 'Терминал'), ('AIRFIELD', 'Лётное поле'), ('SECURE', 'Зона повышенной безопасности')], max_length=20)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'На рассмотрении'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
