# Generated by Django 5.1.4 on 2025-06-11 13:51

import access_control.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_passrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passrequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='passrequest',
            name='end_date',
            field=models.DateField(default=access_control.models.default_end_date, help_text='Дата, до которой нужен пропуск', validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AddField(
            model_name='passrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passrequest',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='passrequest',
            name='access_zone',
            field=models.CharField(choices=[('TERMINAL', 'Терминал'), ('AIRFIELD', 'Лётное поле'), ('SECURE', 'Зона повышенной безопасности')], max_length=50),
        ),
        migrations.AlterField(
            model_name='passrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'На рассмотрении'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20),
        ),
    ]
