# Generated by Django 5.1.4 on 2025-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_remove_passrequest_updated_at_passrequest_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('TERMINAL', 'Терминал'), ('AIRFIELD', 'Лётное поле'), ('SECURE', 'Зона безопасности')], max_length=20)),
                ('required_access_level', models.IntegerField(choices=[(1, 'Базовый (Терминал)'), (2, 'Средний (Лётное поле)'), (3, 'Высокий (Зона безопасности)'), (4, 'Полный (Все зоны)')], default=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='airportpass',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Базовый (Терминал)'), (2, 'Средний (Лётное поле)'), (3, 'Высокий (Зона безопасности)'), (4, 'Полный (Все зоны)')], default=1),
        ),
        migrations.AlterField(
            model_name='airportpass',
            name='access_zone',
            field=models.CharField(choices=[('TERMINAL', 'Терминал'), ('AIRFIELD', 'Лётное поле'), ('SECURE', 'Зона повышенной безопасности')], max_length=10),
        ),
    ]
