# Generated by Django 5.1.4 on 2025-06-12 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_accesszone_airportpass_access_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesszone',
            options={'verbose_name': 'Зона доступа', 'verbose_name_plural': 'Зоны доступа'},
        ),
        migrations.AlterModelOptions(
            name='airportpass',
            options={'verbose_name': 'Пропуск', 'verbose_name_plural': 'Пропуска'},
        ),
        migrations.RemoveField(
            model_name='airportpass',
            name='access_zone',
        ),
        migrations.AddField(
            model_name='airportpass',
            name='access_zones',
            field=models.ManyToManyField(related_name='passes', to='access_control.accesszone'),
        ),
        migrations.AlterField(
            model_name='accesszone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accesszone',
            name='zone_type',
            field=models.CharField(choices=[('TERMINAL', 'Терминал'), ('AIRFIELD', 'Лётное поле'), ('SECURE', 'Зона безопасности')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='airportpass',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='airportpass',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner', 'is_active'), name='unique_active_pass_per_user'),
        ),
    ]
