# Generated by Django 5.1.4 on 2025-06-12 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_alter_accesszone_options_alter_airportpass_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesszone',
            options={},
        ),
        migrations.AlterModelOptions(
            name='airportpass',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='airportpass',
            name='unique_active_pass_per_user',
        ),
        migrations.RemoveField(
            model_name='airportpass',
            name='access_zones',
        ),
        migrations.AddField(
            model_name='airportpass',
            name='access_zone',
            field=models.CharField(choices=[('TERMINAL', 'Терминал'), ('AIRFIELD', 'Лётное поле'), ('SECURE', 'Зона повышенной безопасности')], default=datetime.date(2025, 6, 12), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesszone',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='accesszone',
            name='zone_type',
            field=models.CharField(choices=[('TERMINAL', 'Терминал'), ('AIRFIELD', 'Лётное поле'), ('SECURE', 'Зона безопасности')], max_length=20),
        ),
        migrations.AlterField(
            model_name='airportpass',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 6, 12)),
        ),
    ]
