# Generated by Django 5.1.4 on 2025-06-12 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_alter_accesszone_options_alter_airportpass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesszone',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='airportpass',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='airportpass',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
