# Generated by Django 5.1.4 on 2025-06-12 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0008_alter_accesszone_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('GRANTED', 'Доступ разрешён'), ('DENIED', 'Доступ запрещён'), ('ALERT', 'Попытка доступа в запрещённую зону')], max_length=10, verbose_name='Тип попытки')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('details', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('pass_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.airportpass', verbose_name='Пропуск')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.accesszone', verbose_name='Целевая зона')),
            ],
        ),
    ]
