# Generated by Django 5.1.4 on 2025-03-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('passport_series', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=10)),
                ('flight', models.CharField(max_length=100)),
            ],
        ),
    ]
