# Generated by Django 5.1.4 on 2025-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspicious_status', models.IntegerField(choices=[(0, 'Не подозрительный'), (1, 'Подозрительный')], default=0)),
            ],
        ),
    ]
