# Generated by Django 5.1.4 on 2025-03-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
