# Generated by Django 5.1.4 on 2025-03-18 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_registration_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
    ]
